// src/MiningMonitor.Web/ClientApp/components/Header.tsx
import * as React from 'react';
import { Link } from 'react-router-dom';

import * as Icon from 'react-feather';
import { Nav, Navbar, NavItem } from 'reactstrap';

export const Header: React.SFC = () => (
    <>
        <Navbar dark fixed="top" color="primary navbar-expand">
            <Link to="/" className="navbar-brand">
                Mining Monitor
            </Link>
            <Nav navbar className="mr-auto">
                <NavItem>
                    <Link to="/miners" className="nav-link">Miners</Link>
                </NavItem>
            </Nav>
            <Nav navbar >
                <NavItem>
                    <Link to="/admin" className="nav-link icon" title="Server Administration">
                        <Icon.Settings />
                    </Link>
                </NavItem>
            </Nav>
        </Navbar>
    </>
);

// src/MiningMonitor.Web/ClientApp/src/app/header/header.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'miningmonitor-header',
    templateUrl: './header.component.html'
})
export class HeaderComponent {
}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <a class="navbar-brand" routerLink="/">Mining Monitor</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item" routerLinkActive="active">
                <a class="nav-link" routerLink="/miners">Miners</a>
            </li>
            <li class="nav-item" routerLinkActive="active">
                <a class="nav-link" routerLink="/alerts">
                    Alerts <mm-alert-badge>
                    </mm-alert-badge>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item" title="Server Administration" routerLinkActive="active">
                <a class="nav-link" routerLink="/admin">
                    <fa-icon [icon]="faCog" size="lg"></fa-icon> Admin
                </a>
            </li>
            <li class="nav-item" title="Log Out" *ngIf="isLoggedIn">
                <a class="nav-link" routerLink="/logout">
                    <fa-icon [icon]="faSignOutAlt" size="lg"></fa-icon> Log Out
                </a>
            </li>
        </ul>
    </div>
</nav>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
