// src/MiningMonitor.Web/ClientApp/components/miner/MinerForm.tsx
import * as React from 'react';

import { Button, Col, Form, FormGroup, FormText, Label } from 'reactstrap';

import autobind from 'autobind-decorator';

import { Miner } from '../../models';
import { FormInput } from '../common';

interface Props {
    miner?: Miner;
    validation?: { [key: string]: string[] };
    onSubmit?: (miner: Miner) => void;
}

interface State {
    displayName: string;
    address: string;
    port: string;
    collectData: boolean;
}

export class MinerForm extends React.Component<Props, State> {
    public constructor(props: Props) {
        super(props);
        this.state = this.createState(props.miner);
    }
    public componentWillReceiveProps(props: Props) {
        if (props.miner === this.props.miner) {
            return;
        }
        this.setState(this.createState(props.miner));
    }
    @autobind
    public change(event: React.ChangeEvent<HTMLInputElement>) {
        this.setState({
            ...this.state,
            [event.target.name]: event.target.type === 'checkbox' ?
                event.target.checked :
                event.target.value,
        });
    }
    @autobind
    public submit(event: React.ChangeEvent<HTMLFormElement>) {
        event.preventDefault();
        if (this.props.onSubmit) {
            this.props.onSubmit({
                ...this.props.miner,
                displayName: this.state.displayName,
                address: this.state.address,
                port: +this.state.port || null,
                collectData: this.state.collectData,
            });
        }
    }
    public render() {
        return (
            <>
                <Form className="miner-form" onSubmit={this.submit}>
                    <fieldset disabled={!!this.props.miner.collectorId}>
                        <FormGroup row>
                            <Label for="name" sm={2}>
                                Name
                            <small className="form-text text-muted">Optional</small>
                            </Label>
                            <Col sm={10}>
                                <FormInput
                                    id="displayName"
                                    name="displayName"
                                    type="text"
                                    value={this.state.displayName || ''}
                                    onChange={this.change}
                                    placeholder={this.props.miner ? this.props.miner.name : '127.0.0.1:3333'}
                                    validation={this.props.validation}
                                />
                            </Col>
                        </FormGroup>
                        <FormGroup row>
                            <Label for="address" sm={2}>Address</Label>
                            <Col sm={10}>
                                <FormInput
                                    id="address"
                                    name="address"
                                    type="text"
                                    value={this.state.address || ''}
                                    onChange={this.change}
                                    placeholder="127.0.0.1"
                                    validation={this.props.validation}
                                />
                            </Col>
                        </FormGroup>
                        <FormGroup row>
                            <Label for="port" sm={2}>Port</Label>
                            <Col sm={10}>
                                <FormInput
                                    id="port"
                                    name="port"
                                    type="number"
                                    value={this.state.port || ''}
                                    onChange={this.change}
                                    placeholder="3333"
                                    validation={this.props.validation}
                                />
                            </Col>
                        </FormGroup>
                        <FormGroup row>
                            <Label for="collectData" sm={2}>Data Collection</Label>
                            <Col sm={{ size: 10 }}>
                                <FormGroup check>
                                    <Label check>
                                        <FormInput
                                            id="collectData"
                                            name="collectData"
                                            type="checkbox"
                                            checked={this.state.collectData}
                                            onChange={this.change}
                                            validation={this.props.validation}
                                        /> Enabled
                                </Label>
                                </FormGroup>
                            </Col>
                        </FormGroup>
                        {!this.props.miner.collectorId ?
                            <Button outline color="info">Save Changes</Button> :
                            null}
                    </fieldset>
                </Form>
            </>
        );
    }
    private createState(miner: Miner) {
        miner = miner || {} as Miner;
        return {
            displayName: miner && miner.displayName,
            address: miner && miner.address,
            port: (miner && miner.port) ? String(miner.port) : null,
            collectData: miner && miner.collectData ? true : false,
        };
    }
}

// src/MiningMonitor.Web/ClientApp/src/app/miner/miner-form/miner-form.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

import { Miner } from '../../../models/Miner';

@Component({
    selector: 'mm-miner-form',
    templateUrl: './miner-form.component.html',
    styleUrls: ['./miner-form.component.scss']
})
export class MinerFormComponent {
    @Input()
    public miner: Miner = {
        displayName: null,
        address: null,
        port: null,
        collectData: null
    };
    @Input()
    public validationErrors: { [key: string]: string[] } = {};

    @Output()
    public save = new EventEmitter<Miner>();

    public Submit() {
        this.save.emit(this.miner);
    }
}

<form (submit)="Submit(); $event.preventDefault()">
  <fieldset [disabled]="miner.collectorId">
    <div class="form-group row">
      <label for="displayName" class="col-sm-2">
        Name
        <small class="form-text text-muted">Optional</small>
      </label>
      <div class="col col-sm-10">
        <input
          name="displayName"
          class="form-control"
          [placeholder]="miner.name ? miner.name : '127.0.0.1:3333'"
          [ngClass]="{ 'is-invalid': validationErrors.displayName }"
          [(ngModel)]="miner.displayName"
        />
        <small
          class="invalid-feedback"
          *ngFor="let message of validationErrors.displayName"
        >
          {{ message }}
        </small>
      </div>
    </div>
    <div class="form-group row">
      <label for="address" class="col-sm-2"> Address </label>
      <div class="col col-sm-10">
        <input
          type="text"
          name="address"
          class="form-control"
          placeholder="127.0.0.1"
          [ngClass]="{ 'is-invalid': validationErrors.address }"
          [(ngModel)]="miner.address"
          valid="false"
        />
        <small
          class="invalid-feedback"
          *ngFor="let message of validationErrors.address"
        >
          {{ message }}
        </small>
      </div>
    </div>
    <div class="form-group row">
      <label for="port" class="col-sm-2"> Port </label>
      <div class="col col-sm-10">
        <input
          type="number"
          name="port"
          class="form-control"
          placeholder="3333"
          [ngClass]="{ 'is-invalid': validationErrors.port }"
          [(ngModel)]="miner.port"
        />
        <small
          class="invalid-feedback"
          *ngFor="let message of validationErrors.port"
        >
          {{ message }}
        </small>
      </div>
    </div>
    <div class="form-group row">
      <label for="collectData" class="col-sm-2"> Data Collection </label>
      <div class="col col-sm-10">
        <label>
          <input
            type="checkbox"
            name="collectData"
            [(ngModel)]="miner.collectData"
          />
          Enabled
        </label>
      </div>
    </div>
    <button
      type="submit"
      class="btn btn-outline-info"
      *ngIf="!miner.collectorId"
    >
      Save Changes
    </button>
  </fieldset>
</form>
